name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."



